---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy"
stores:
  yaml:
    indent: 2
