apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:OMn5BGpTfN6wiqURh2x9RAi9+npjcbtRbrD79oQrHnWlEqH8hOk77w==,iv:tcfoZiX8OItQ8JZ9/8nl/Ruz3KS1F9W9+dJrCKi4++Q=,tag:ikp1qDfXimbeDvlT/UXw3Q==,type:str]
sops:
  age:
    - recipient: age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWTUvelNkVEtGVU1lM2x2
        VHlRNHN6SWE2WE9kb00xOE0rd0Uwblk2dVNBCkpXbDNjeUhJUkZRQS9GUHlLUURx
        TmlqY1VtdzFDRG5CR3BRbkJLNlZhN3MKLS0tIFJGWFduOHY5Q3MxQVppNTVERzhL
        T0VyMDBiNHpGRGVzK3dES0NOR3VReGsKa75h0SdztmnGNPDZY4PqgAihM3xMBW1C
        a+wWI+UtLLOq2fx12GWZ/BcGAZK7S3c2GFBQn8OpjJWGwBKYWwtW2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T12:26:14Z"
  mac: ENC[AES256_GCM,data:/zUGKRkBkuVgct4uKVrj0qFWbXLRep/5FXc6DSR/jHeZJI8W+kv+FKk4PgkGhm1fGTr/UTNpnE5gm7t1ZTGmjNAAWOlgYQxwPNHr5Q52YOeEf5QAkw/DsSGV6+Run6H+jGSWyFqIns7/V+9KZJDQCYC+n4Cn/4VjSLCHQ4qHbL0=,iv:FCUrXkIMsnFkAqtbPeDqFTvDQK+UaGuLuUo7l6VcO3c=,tag:MaUnuWe8Jfl2IR0GUoYsjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
