apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:YNqvV6geiaaCYTrquTWV/emPEVt5USYoszwvEB/8I5thMpgoOqqKsg==,iv:4CWdeg6h24Vr5n6yC9gWML4bJkL3lmcKd2cHbdX7a0w=,tag:k9saSGJ6sIvJR6MA7GlMCQ==,type:str]
sops:
  age:
    - recipient: age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4K1ZMaGYzNjRpQ0UzQVYw
        TFdjeHY0aGNNVGdmdDdQMjJ5THZOaEo4Ukc4CjRPOXRGVThOWHRkUXd3WllLSHVF
        Y295c2FYblVReUNac3RZUmtyWmtKUzQKLS0tIHZaZGFzZVNzV25hNTR4SU00OWpR
        WUtDSEhOdDlxRThoZ0d1VUtSSEhTdE0KKMiKcjeYWNovzFtIXubSgO052YzyZOWA
        RP2gPdWdYI9bhjNrbgeRWy0BQNSg8bS/Y207I72uvP6d3ZhFLTBdtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T11:03:22Z"
  mac: ENC[AES256_GCM,data:DExxoKuObusY0bYAqf9NI/34jJsra1ioJGRInQnBSj1udSLJX8gB9+tV3YHqZhBaKyme07fr2VXdKtQ9LOTBsM7m1nuthAJNFF7R9m5Uxna4kxTujOCEStM96gXXiOizz6yfkuO3f2AnzPWelOHOWp7vzuH8uPjtZBzqTghCvgA=,iv:OBFK8ZI0HMvjAtUUURxacwQmvh2BxseDIMt5cO9WfJg=,tag:pqUJClyDqGb3FbLhv55wnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
