---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}-k8s"
spec:
  restic:
    accessModes: ["${VOLSYNC_SNAP_ACCESSMODES:-ReadWriteOnce}"]
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-5Gi}"
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    moverSecurityContext:
      fsGroup: ${VOLSYNC_PGID:-568}
      runAsGroup: ${VOLSYNC_PGID:-568}
      runAsUser: ${VOLSYNC_PUID:-568}
    pruneIntervalDays: 7
    repository: "${APP}-volsync-minio-secret"
    cacheStorageClassName: "${VOLSYNC_CACHE_STORAGECLASS:-longhorn-cache}"
    retain:
      daily: 7
      hourly: 24
      weekly: 5
      monthly: 3
    storageClassName: "${VOLSYNC_STORAGECLASS:-longhorn}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-longhorn}"
  sourcePVC: "${APP}"
  trigger:
    schedule: "0 * * * *"
