apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:PhY1CbmMSKb0,iv:VfwvL3YxnlCvUFSGfZdvNkfoztIuwRZZMVS0pTvHvSU=,tag:m1qRDE8S9gBwJzIbykFy8A==,type:str]
sops:
  age:
    - recipient: age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWREJrWnNKQTN6cTZrSEln
        dmhCRzZWc21uNmJOU2xESmJzR1NOTTN0b1VzCm84WGRhSGZmR1dxZjUxUWwxR2Fz
        Ri96N3JlOXpicVdGc3dpSGpnYW9DVlEKLS0tIEU5WUxpL2pJRHE0NHkyWFdiSFpZ
        YmxDdDVFMXUyOC9odWFpZFZIYXVicTQKQuqmC3COIs+PIuN5g5/IBI0KOww+7CsM
        R8d3Ze21YkMq9h2NvVBmjgjVKpP2XQJblR4a3pifg1riqnQ+4oxacQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T11:03:22Z"
  mac: ENC[AES256_GCM,data:Tc1JYw3j/VJ25+j5vr+rLXUveMS3Y5ZXtzIzFL9csEQqTd75S4aLBcvdqPvPOIqu3PqfviIqQk8c8LtRWHuEiIKo0l5VIHDv5zx0rY2eqeC6NP8z5Jgq9urR3qS4DNCIsI2bFlqkgde7bL7xblJ3meeSeVg2hMV3Pa6UTHRH4ms=,iv:/k0a4QQxACsTKfu07yXiwY7/Xd5CJycRv7U4XgyCM4o=,tag:hIN7C2kBuax2O7kpGwqBHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
