apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:FuF3PcA3JRGE,iv:P6cRin6aeeM92ebeVRVusxTRsMBKVmF/SldVD3nihUo=,tag:tVZ1yEUjl1uxqvrCg2flMA==,type:str]
sops:
  age:
    - recipient: age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNDIxV25FVllKa0JpM1Bh
        U1cyRXBJbE1FMmJxVWdNOXlOTVJnaURMWkNrCnU4RVdHb1QvRU9lOTVvRWprelZQ
        bkJsd2NhYUcyRUUwYTJRUFVLdXNybHMKLS0tIHRjQ2w3VXkvRlJsbVlxN3lLVGNB
        Q1dFQ3BSaDh1TzZ0Z21NWjlNVDFrUHcKoBuFzXNNMXyyqh3Rk/T4EctLZynN94/q
        xAXteSgVn6Wi7mPqsHLVSB0Nst+OSpgj+sIHwuKYHs9Qo4mtBtIWhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T12:26:14Z"
  mac: ENC[AES256_GCM,data:p+1nf9Gf13c6wv81M8FP7AXk3SxOn+5par94DMeHsDMrTYFA+UYGFSwqPwhDAbu7wG9i9a7YIz0Khkv7BLYmg0JxJfo6z5bvjCa1p38WBQVyU6st/yDzFlkRoWh1ny9pvZqYYs00HLWmUtoaFERo0MqXMAOoRq+UwKQLwmFlj30=,iv:02NA5BOqQg2B7RpHzGOxtiCO2HF5qUCukpJfbV0cYQQ=,tag:HmRIBXh3HihbPu/lSYIugA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
