apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:eJf0EqcAdGoaD3zyWBe7rTumhaEnZrWC1E2pndjFCR4=,iv:oq+kJgd6Ss9PmlbQh3Ppq1YrSrgiFwIYaucegjcwoxE=,tag:H/iJGyAgRABf65dph1PRZA==,type:str]
sops:
  age:
    - recipient: age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNHRlNVcydUV0WFN5UWZQ
        NWVkQ3VQZUpHb1RMZUFSVUpFOEIzSUpVM3dvCmlOM3hPVHYyeUFtKzJzOENhWVJa
        S2tLTnNFTi9BN1Fod1BvVUxJY1JadU0KLS0tIDhpSUl3WHVMOHkrODJtWUw0R3Yy
        ckRMK1hTUzZDcTNlTTlPYjJhUzF2eUkKAC0PwtdFc2vy63M5fLr+4ASk3p7RXr0D
        4zave1FcCoFQyI4Q880CsFKT4VZ1WEIHK/eMamCcgrPnTZtZU4R/0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T12:26:14Z"
  mac: ENC[AES256_GCM,data:mESNsED8I2791MNtLfTlw4AlxIYDZFSXFiQKmqEt62A1Ce7AzXEd5prhGTeDWAWbmE4GaGe8rx8GyspDNyG+mMdx1AeerTCIGbv6oaTknvLyEb5Czb/YLzgk3mlaiNpPHdZ3r15gJS1GfE8ouEM1qpUZqd5r3Yu6+ZNlIPtm1eQ=,iv:VTx5Ca9mcFp8WMJacPInqi7KwC7mqJxXgXErZkDp5yQ=,tag:3bcYcS5EpjON2GsK5L/nEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
