apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:9J5dSxgooQ/g2RJzI31EttQzKfJwfRdFlUwFLepZBWk=,iv:bNaTLwxVYX9RY8a8HKAIQIgtdJulqMxHJY8z5kBxAO4=,tag:4QVwUUjJQ7pvATlez3o1TQ==,type:str]
sops:
  age:
    - recipient: age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveEVVakxLcjNGY3RmTmV1
        TzZtUHIvcVRpL2kxbHNQR3B3aWo2QXFxRkhVCjNoOXhzZk9ZaTlJbU8zZUlqMVNK
        VEhiTmczM3hlN09FMFg2R1Y3VnZSbk0KLS0tIGF2em94WEV2TjJvY3BheFJ5NzZI
        N05yZkVYSHdwblZFUk5SWWZGQjBQckEK1k3FIF7eM+VrQXG7ND+1Y8Gn+ekW8UXu
        tA0cQ3dXEfPvh53EuQ2gG/tXh7sSbz3wTmQU3Gmt24u7Z3R5kxifmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T11:03:22Z"
  mac: ENC[AES256_GCM,data:iyzwZg5vNzL7tfji2592xI+QAKK4eBr8aFm55FOTbdhUn6wBek0p/Odp3hnMd9EWzxMd+HRCxd1F51LtftCcdVOKM6jvL+QN09WGyk9zQq22wUi8hbEGxVY98jIbdk+EoFQ42tsWT4YqD+8rXAS25dX0FMEbYJzx3hUNU8IVhcM=,iv:BF2fAQ/SKzGDH50H3XbJDByH25jGapY3rkTovCQat8Q=,tag:wP0gnxJWsBZiRog8YQe91Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
