apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:uuOsvM7Bln1BPw7PUqQanRZCgZ9bTf69HYHMTSIykVNILpyHAUAjQXLZsIXySrlDk8yCWZCEbk519gfoNjQsiyIzXaDst63dXwczH9GXTYHVUWURUGNBCISH8uijtmoAZZ8Ny+5FQrMyESE6Wm1RHbwa8QUcJGHbzwUVp12xSbWVZCh5xMm45hSB+XUPldjTcb+xsSVSSGXRGfUCmlyJKszW1YL2E9B2Dfuvexp9BqcHl4Sl,iv:0kGdu3VG5ZzmCMkfUg/fV/wbJQ5sPMuKUXpbU5S6zkM=,tag:fS767Alkkl9TVG/WjRUdqQ==,type:str]
sops:
  age:
    - recipient: age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaUdqc3BKL2VMdC9ET2xR
        NnJHUlpoZm1VcVlsRy9Kb1NEK2RuMVJNWGtzCmhpV1V3VVphTmtibjFkVWx2aWJU
        OERCZkV4WmRqR25obFl6dnY2NHQyWmMKLS0tIGdoeDhObFNXQ051ZFFGWW5aMVZ1
        VUVkaEdYTnF4SWcyTnZjdGtseTc3VUEKmPC/uQpmWo3t+BYILD9nKJFDNJ7lMAsn
        g+xB029aQeP8KL0hVw7lAZd27V5TLzCj2h9iwBg+elheotSD5sVUew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T12:26:14Z"
  mac: ENC[AES256_GCM,data:jgIV386o3hPHA/H9A6QERmeeqj3IF+FFwF39eir8PBEwU281Ei+hKn36eunkMJc6W0nwKdQoX18g32Feev+ng3m6JfJwn4InBvu9wIFfQmhrHMUEKrFIUEePb4j1Kmsn3GL7h4rtzyrxNqGcObG/gFTfV8c9tN5vsxxouTJfGNM=,iv:8oB2YmDVQ64I4TKcDGcktz5zojPDBXdcriqxRuNvwqo=,tag:Kfd1TS9I8U6iigQTNmLW1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
