apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:HxgKUd2LHSAM0tZ5yFMuzswnn5ctoiB9g1DDhs0Gc4Gr/qVpDaZyGnf2NXzYYNyH9vQyacR6VF+AgZuAJFMv5QMaUQXsU2ChAhcSFoPWm1+sAY9z+1u1aDxurcjbAcelXlL0ovTUGIFPw7H68RfyTU4sqOfsYvuqbP+ILKeGgaqSUUG8Kg9HeEl/tEs3d07WYELqanY1elL7Df8WKGhpVn4ZnuDXRgVRCw4USrmbxcG59N6+,iv:MtGOWX2QezjfDYGzgwUAoau3vmPzoURSWhzOc1TZd2E=,tag:9A+ETQnXuR07V6i/B8zfcw==,type:str]
sops:
  age:
    - recipient: age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqN085NElTNjJnL2w3c1JP
        VGhTdGlSWDN2bWp0M3NkV1d5ODZvZk1kTlZvCjJWUVVWMDlTZ0NBNG92eUVFZ0Yw
        MUpicVUzOEJicHJSa0IwN0tyYVpBSXMKLS0tIHM3RGZkZ2l5MGZQdlhJbEZ1UXdl
        SWorOTRYUjlTQjlWMXV5RzBsVmFFS2sKDicPC43HXr5uc4S7DmR3Y61RON/NtLG5
        2RsNd6DQqP6eFDTxj96Vr5qhp3Z064vdBOFFVJNWHYxb+viz4jOL/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T11:03:22Z"
  mac: ENC[AES256_GCM,data:Os2Npg/S/5/JNBPZ8WThhziOFcoillj+IscyIdwMIzCIL/QHHOnRQW1yM1xVtx/NYWOrIWqJXd/ybQW0fofOjG9aD5mZ//Qqrx5F6FZ7/2UszdoBzMkSmRc8Z7uExI84agGdLXwbnk1J/LpYfcfj5rgaol2hV6vJsv43DYISdwA=,iv:uKAwVhYtzuomD8BNAe7tRny2DcL0UWULhV2W4d4zHu0=,tag:EWBgg1zDykpdlh8q+TB5hA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
