apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:mEWdKMG+rzto5TKnUQywlp8FKVOc/Qh75d5zSNvMypgIptFgzW6CYg==,iv:0OsnT+R59eVe5xNuwjPxCJALRYiLcjULwH3Z43hUG9c=,tag:/XI9gG0bvNnLtIuaUc/dAg==,type:str]
sops:
  age:
    - recipient: age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYjY0dE13VXAzem9vUFlD
        STRaOWlvOVpwS21GWk9RU05YdFdidktMQ2dnCmdlaDNSSVlueFdIbmJ3bzhDSFJI
        UFp3c2ZRcG14VWNyZ0R1QXdKYVJ5czgKLS0tIGRtdnVabnpDTjVYeTEwcnNrTmlm
        TG1Kd2RMRms0dnhhUjMwZHg5eklyTFUKgNKvGH7Pl2v/7EJ0NzRSqWJd98T+AkYW
        TtR4LlBZc7AUVeJBN1eTN6HQ60RSqbwSdWilcTr3DvuzwxGfD0Kv1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T11:03:22Z"
  mac: ENC[AES256_GCM,data:WpyMNW6pJrJKnGYTlP43NbkMvO5dLDUjwwpjG3NrdjsOyFCAeLQRwGmTiXKP1i69Hbk44N/laP13t1i8/EAO4yIToFEeqQzTysiLg3VvDc68dTRIqBAzDpRxEHs08Zv8+pnbLk2aAf2zW2LgMje3JlPDjGFx41Rp7b+c+nz3aKA=,iv:nmrIAnSH0uWQDTwbT+8Wfwqtap/DFsTo0NJJKR85gww=,tag:lCIc+Psrq8d6d2kH5C0Hig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
