apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0TnrMR8iIiqwhgziXmlkOIiQsGabhkZQA90xYuwbRzeK1tlpPsDtzg==,iv:T+h0Ct/C8jDuV8atgiaolraB2C0DmLVx7PJd0sxb/Uc=,tag:ywFSc1EtzMnmeWhJ/+cUQQ==,type:str]
sops:
  age:
    - recipient: age1msxtmv5vvk6624gj3jyjynnh5rm6sd9hlkrhyxau2ckvd5c2hsfsdctzvy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSzYzYmZpSm5sZHBUbWFi
        QXFEdU0rVTBWbkRyRE1qdnZURmEvaGozamt3CkRWVFZISlJtL2pDb3F6VFZYTlR5
        U0pXd2dWdTVRTmhZS0ZaWHFqbjd5RlUKLS0tIEhYZDJua0QydXFuajdVdElVY0Mz
        aWxJMjFPQkZXTFNidzQzc3dsbDJQRm8KQvcJJYwkZtLUWQgl5MoDpSD1IJ7bTA8M
        JMGW03s0+mN4yuylhZEhyo7uWjaW3Gn4JF1h3o3/9usC/frIeQXdyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T12:26:14Z"
  mac: ENC[AES256_GCM,data:p0zlzhOAXIfeg1sAacu34jgcRFWoFb2TmUryPO1uNlvHwqeENLUUYdXUodebwbl4+WcZTAei0SzSW2ivmXFyUSbsGsX9wQ0fHHWXqesQwinQM6eXIfjTYlUzXjC5g9Qic4EUhjTgAhn0ug/v8tqjtAN1AtFeYMnZnLfS9+cGh3I=,iv:63Wu9aQiwrTuLwHNqsgfAblCyGO5iEwJ7QZCbxNNQts=,tag:ul1SjCZdQAWJJ3vk5RjevA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
