---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: storage
      version: 1.9.1
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    monitoring:
      enabled: true
    persistence:
      defaultClassReplicaCount: 3
    defaultSettings:
      # defaultDataPath: /var/lib/longhorn
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      storageReservedPercentageForDefaultDisk: 10
      createDefaultDiskLabeledNodes: true
      defaultReplicaCount: 3
      orphanAutoDeletion: true
      storageMinimalAvailablePercentage: 10
      replicaAutoBalance: best-effort
      defaultDataLocality: best-effort
